/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DetectionResult } from "./DetectionResult";
import { DetectionResultCountArgs } from "./DetectionResultCountArgs";
import { DetectionResultFindManyArgs } from "./DetectionResultFindManyArgs";
import { DetectionResultFindUniqueArgs } from "./DetectionResultFindUniqueArgs";
import { CreateDetectionResultArgs } from "./CreateDetectionResultArgs";
import { UpdateDetectionResultArgs } from "./UpdateDetectionResultArgs";
import { DeleteDetectionResultArgs } from "./DeleteDetectionResultArgs";
import { Email } from "../../email/base/Email";
import { CreateDetectionResultInput } from "../CreateDetectionResultInput";
import { DetectionResultService } from "../detectionResult.service";
@graphql.Resolver(() => DetectionResult)
export class DetectionResultResolverBase {
  constructor(protected readonly service: DetectionResultService) {}

  async _detectionResultsMeta(
    @graphql.Args() args: DetectionResultCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DetectionResult])
  async detectionResults(
    @graphql.Args() args: DetectionResultFindManyArgs
  ): Promise<DetectionResult[]> {
    return this.service.detectionResults(args);
  }

  @graphql.Query(() => DetectionResult, { nullable: true })
  async detectionResult(
    @graphql.Args() args: DetectionResultFindUniqueArgs
  ): Promise<DetectionResult | null> {
    const result = await this.service.detectionResult(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DetectionResult)
  async createDetectionResult(
    @graphql.Args() args: CreateDetectionResultArgs
  ): Promise<DetectionResult> {
    return await this.service.createDetectionResult({
      ...args,
      data: {
        ...args.data,

        email: args.data.email
          ? {
              connect: args.data.email,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => DetectionResult)
  async updateDetectionResult(
    @graphql.Args() args: UpdateDetectionResultArgs
  ): Promise<DetectionResult | null> {
    try {
      return await this.service.updateDetectionResult({
        ...args,
        data: {
          ...args.data,

          email: args.data.email
            ? {
                connect: args.data.email,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DetectionResult)
  async deleteDetectionResult(
    @graphql.Args() args: DeleteDetectionResultArgs
  ): Promise<DetectionResult | null> {
    try {
      return await this.service.deleteDetectionResult(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Email, {
    nullable: true,
    name: "email",
  })
  async getEmail(
    @graphql.Parent() parent: DetectionResult
  ): Promise<Email | null> {
    const result = await this.service.getEmail(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CreateDetectionResultInput)
  async DetectPhishing(
    @graphql.Args()
    args: CreateDetectionResultInput
  ): Promise<CreateDetectionResultInput> {
    return this.service.DetectPhishing(args);
  }
}
